-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.clients (
  client_id uuid NOT NULL,
  client_name text NOT NULL,
  company_domain text NOT NULL,
  company_website text NOT NULL,
  industry text,
  target_region text NOT NULL DEFAULT 'us'::text,
  competitors jsonb NOT NULL DEFAULT '[]'::jsonb,
  competitors_url jsonb,
  topics jsonb NOT NULL DEFAULT '[]'::jsonb,
  synced_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clients_pkey PRIMARY KEY (client_id)
);
CREATE TABLE public.clusters (
  cluster_id text NOT NULL,
  client_id uuid NOT NULL,
  cluster_name text NOT NULL DEFAULT ''::text,
  synced_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT clusters_pkey PRIMARY KEY (cluster_id, client_id),
  CONSTRAINT clusters_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);
CREATE TABLE public.sov_weekly (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  client_id uuid NOT NULL,
  cluster_id text NOT NULL,
  cluster_name text,
  week_date date NOT NULL,
  top_companies jsonb,
  selected_queries jsonb,
  top_sources jsonb,
  service text,
  synced_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sov_weekly_pkey PRIMARY KEY (id),
  CONSTRAINT sov_weekly_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);
CREATE TABLE public.ai_responses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  client_id uuid NOT NULL,
  cluster_id text NOT NULL,
  cluster_name text,
  week_date date NOT NULL,
  platform text,
  query text,
  citations_data jsonb,
  answers_list jsonb,
  citations_list jsonb,
  synced_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_responses_pkey PRIMARY KEY (id),
  CONSTRAINT ai_responses_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);
CREATE TABLE public.sov_tracking (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  run_id uuid NOT NULL,
  client_id uuid NOT NULL,
  cluster_id text NOT NULL,
  competitor_name text NOT NULL,
  week_date date NOT NULL,
  current_sov numeric,
  previous_sov numeric,
  rolling_mean numeric,
  rolling_std numeric,
  z_score numeric,
  sov_delta_pp numeric,
  alert_flag text,
  is_significant boolean NOT NULL DEFAULT false,
  displacement_flag boolean NOT NULL DEFAULT false,
  displacement_peer text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_sov_this_week numeric,
  client_sov_change_vs_avg numeric,
  alert_reason text,
  CONSTRAINT sov_tracking_pkey PRIMARY KEY (id),
  CONSTRAINT sov_tracking_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);
CREATE TABLE public.investigation_triggers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  run_id uuid NOT NULL,
  client_id uuid NOT NULL,
  trigger_key text NOT NULL,
  cluster_id text NOT NULL,
  competitor_name text NOT NULL,
  competitor_domain text,
  week_date date NOT NULL,
  detection_source text NOT NULL,
  alert_flag text,
  z_score numeric,
  sov_delta_pp numeric,
  blog_post_url text,
  blog_post_title text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'skipped'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_name text,
  cluster_label text,
  shift_type text,
  shift_magnitude numeric,
  shift_in_sd_units numeric,
  client_sov_change numeric,
  correlated_displacement boolean DEFAULT false,
  investigation_priority text,
  triage_reason text,
  CONSTRAINT investigation_triggers_pkey PRIMARY KEY (id),
  CONSTRAINT investigation_triggers_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);
CREATE TABLE public.website_snapshots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  run_id uuid NOT NULL,
  domain text NOT NULL,
  week_date date NOT NULL,
  pages jsonb,
  page_count integer,
  crawl_metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT website_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.investigations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  run_id uuid NOT NULL,
  trigger_id uuid,
  trigger_key text NOT NULL,
  client_id uuid NOT NULL,
  cluster_id text NOT NULL,
  competitor_name text NOT NULL,
  week_date date NOT NULL,
  website_changes jsonb,
  third_party_signals jsonb,
  ai_citation_changes jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT investigations_pkey PRIMARY KEY (id),
  CONSTRAINT investigations_trigger_id_fkey FOREIGN KEY (trigger_id) REFERENCES public.investigation_triggers(id),
  CONSTRAINT investigations_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);
CREATE TABLE public.competitor_feeds (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  domain text NOT NULL UNIQUE,
  feed_url text NOT NULL,
  feed_type text,
  discovery_method text,
  last_success_at timestamp with time zone,
  last_failure_at timestamp with time zone,
  failure_count integer NOT NULL DEFAULT 0,
  retry_after timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT competitor_feeds_pkey PRIMARY KEY (id)
);
CREATE TABLE public.feed_entries_seen (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  domain text NOT NULL,
  entry_id text NOT NULL,
  entry_url text,
  first_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT feed_entries_seen_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sitemap_urls_known (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  domain text NOT NULL,
  url text NOT NULL,
  first_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sitemap_urls_known_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blog_detections (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  run_id uuid NOT NULL,
  client_id uuid NOT NULL,
  domain text NOT NULL,
  url text NOT NULL,
  title text,
  published_at timestamp with time zone,
  week_date date NOT NULL,
  content_type text,
  cluster_id text,
  cluster_relevance text,
  relevance_reason text,
  source text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT blog_detections_pkey PRIMARY KEY (id),
  CONSTRAINT blog_detections_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);
CREATE TABLE public.recommendations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  run_id uuid NOT NULL,
  investigation_id uuid,
  client_id uuid NOT NULL,
  cluster_id text NOT NULL,
  competitor_name text NOT NULL,
  week_date date NOT NULL,
  rec_type text NOT NULL CHECK (rec_type = ANY (ARRAY['offensive'::text, 'defensive'::text])),
  priority text NOT NULL CHECK (priority = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  probable_cause text,
  gap_analysis text,
  action_bullets jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence text,
  evidence_summary text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_name text,
  cluster_label text,
  shift_type text,
  summary text,
  slack_report text,
  timeline text,
  validation_status text DEFAULT 'ok'::text,
  validation_notes jsonb DEFAULT '[]'::jsonb,
  window_weeks integer,
  revenue_opportunity_usd numeric,
  revenue_at_risk_usd numeric,
  revenue_basis text DEFAULT 'none'::text CHECK (revenue_basis = ANY (ARRAY['actual'::text, 'modeled'::text, 'hybrid'::text, 'none'::text])),
  revenue_inputs jsonb,
  CONSTRAINT recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT recommendations_investigation_id_fkey FOREIGN KEY (investigation_id) REFERENCES public.investigations(id),
  CONSTRAINT recommendations_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);
CREATE TABLE public.reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  run_id uuid NOT NULL,
  recommendation_id uuid,
  client_id uuid NOT NULL,
  cluster_id text NOT NULL,
  competitor_name text NOT NULL,
  week_date date NOT NULL,
  internal_report text,
  client_summary text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  cluster_label text,
  priority text,
  validation_status text DEFAULT 'ok'::text,
  validation_notes jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT reports_pkey PRIMARY KEY (id),
  CONSTRAINT reports_recommendation_id_fkey FOREIGN KEY (recommendation_id) REFERENCES public.recommendations(id),
  CONSTRAINT reports_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id)
);
CREATE TABLE public.cycle_runs (
  run_id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sync_date date NOT NULL,
  mode text NOT NULL CHECK (mode = ANY (ARRAY['dry-run'::text, 'sample'::text, 'live'::text])),
  client_filter text,
  status text NOT NULL DEFAULT 'started'::text CHECK (status = ANY (ARRAY['started'::text, 'completed'::text, 'failed'::text])),
  clients_processed integer NOT NULL DEFAULT 0,
  triggers_fired integer NOT NULL DEFAULT 0,
  no_shift_clients integer NOT NULL DEFAULT 0,
  capped_investigations integer NOT NULL DEFAULT 0,
  blog_triggers_fired integer NOT NULL DEFAULT 0,
  total_prompt_tokens bigint NOT NULL DEFAULT 0,
  total_completion_tokens bigint NOT NULL DEFAULT 0,
  total_tokens bigint NOT NULL DEFAULT 0,
  error_message text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  clusters_processed integer,
  competitor_cluster_pairs_evaluated integer,
  investigations_by_type jsonb,
  no_significant_shifts_clients_list jsonb,
  capped_investigations_list jsonb,
  data_quality_errors integer,
  hallucinated_number_metric jsonb DEFAULT '{}'::jsonb,
  quarantine_count integer DEFAULT 0,
  quarantine_by_reason jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT cycle_runs_pkey PRIMARY KEY (run_id)
);
CREATE TABLE public.prompt_log (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  run_id uuid NOT NULL,
  node text NOT NULL,
  model text NOT NULL,
  prompt_tokens integer NOT NULL DEFAULT 0,
  completion_tokens integer NOT NULL DEFAULT 0,
  total_tokens integer NOT NULL DEFAULT 0,
  latency_ms integer,
  error text,
  logged_at timestamp with time zone NOT NULL DEFAULT now(),
  reasoning_tokens integer,
  reasoning text,
  CONSTRAINT prompt_log_pkey PRIMARY KEY (id),
  CONSTRAINT prompt_log_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.cycle_runs(run_id)
);
CREATE TABLE public.sync_state (
  table_name text NOT NULL,
  last_synced_at timestamp with time zone NOT NULL DEFAULT '2000-01-01 00:00:00+00'::timestamp with time zone,
  status text DEFAULT 'ok'::text,
  error_message text,
  updated_at timestamp with time zone,
  CONSTRAINT sync_state_pkey PRIMARY KEY (table_name)
);
CREATE TABLE public.report_data (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  client_id text,
  report_id text,
  ai_visibility_data json,
  website_files_data json,
  schema_data json,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  company_website text,
  company_name text,
  final_points json,
  CONSTRAINT report_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.onboarding (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid UNIQUE,
  company_domain text,
  company_name text,
  target_region text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  status boolean,
  industry text,
  target_audience text,
  competitors jsonb,
  topics jsonb,
  category_tags jsonb,
  primary_goal text,
  tone_preference text,
  average_order_value numeric,
  conversion_rate numeric,
  estimated_ctr numeric,
  currency character varying,
  client_plan text,
  company_website text,
  demo_ready boolean,
  company_description text,
  competitors_url jsonb,
  lead_source text,
  CONSTRAINT onboarding_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_metrics (
  client_id uuid NOT NULL,
  ga4_refresh_token text,
  ga4_property_id text,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  average_order_value numeric,
  conversion_rate numeric,
  estimated_ctr numeric,
  gsc_refresh_token text,
  gsc_site_url text,
  CONSTRAINT user_metrics_pkey PRIMARY KEY (client_id)
);
CREATE TABLE public.queries_groups_data (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  queries_groups_data jsonb,
  client_id uuid,
  updated_at timestamp with time zone,
  CONSTRAINT queries_groups_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.keywords_groups_data (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  keywords_groups_data jsonb,
  client_id uuid,
  CONSTRAINT keywords_groups_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_scraped_data_cache (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  url text,
  source text,
  summary text,
  count bigint,
  last_refreshed timestamp with time zone,
  CONSTRAINT company_scraped_data_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.selection_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid,
  event_type character varying,
  platform character varying,
  query_text text,
  response_text text,
  was_selected boolean,
  competitors_mentioned ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  attribution_event_id uuid,
  revenue_attributed numeric,
  CONSTRAINT selection_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.recommendations_backup_tiage (
  id uuid,
  run_id uuid,
  investigation_id uuid,
  client_id uuid,
  cluster_id text,
  competitor_name text,
  week_date date,
  rec_type text,
  priority text,
  probable_cause text,
  gap_analysis text,
  action_bullets jsonb,
  confidence text,
  evidence_summary text,
  created_at timestamp with time zone,
  client_name text,
  cluster_label text,
  shift_type text,
  summary text,
  slack_report text,
  timeline text,
  validation_status text,
  validation_notes jsonb
);
CREATE TABLE public.reports_backup_tiage (
  id uuid,
  run_id uuid,
  recommendation_id uuid,
  client_id uuid,
  cluster_id text,
  competitor_name text,
  week_date date,
  internal_report text,
  client_summary text,
  created_at timestamp with time zone,
  cluster_label text,
  priority text,
  validation_status text,
  validation_notes jsonb
);
CREATE TABLE public.scout_decision_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  client_id uuid,
  cluster_id text NOT NULL,
  cluster_label text,
  week_date date,
  primary_competitor text,
  primary_delta_pp double precision,
  delta_client_pp double precision,
  triage_severity text,
  investigation_priority text,
  noise boolean DEFAULT false,
  field jsonb,
  created_at timestamp with time zone DEFAULT now(),
  floor_set jsonb,
  severity_floor_version text,
  graduation_regime text,
  CONSTRAINT scout_decision_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scout_outcomes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recommendation_id uuid NOT NULL,
  run_id uuid NOT NULL,
  client_id uuid,
  cluster_id text NOT NULL,
  week_date date,
  execution_status text NOT NULL DEFAULT 'proposed'::text CHECK (execution_status = ANY (ARRAY['proposed'::text, 'accepted'::text, 'executed'::text, 'verified'::text, 'declined'::text])),
  baseline_client_sov_pp double precision,
  baseline_competitor_sov_pp double precision,
  baseline_primary_competitor text,
  baseline_snapshot_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  competitor_name text,
  window_weeks integer,
  window_elapsed_at date,
  current_client_sov_pp numeric,
  sov_delta_pp numeric,
  recovered boolean,
  executed boolean,
  field jsonb,
  measured_at timestamp with time zone,
  baseline_revenue_usd numeric,
  revenue_at_risk_usd numeric,
  current_revenue_usd numeric,
  revenue_delta_usd numeric,
  revenue_basis text DEFAULT 'none'::text CHECK (revenue_basis = ANY (ARRAY['actual'::text, 'modeled'::text, 'hybrid'::text, 'none'::text])),
  CONSTRAINT scout_outcomes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scout_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid,
  recommendation_id uuid,
  run_id uuid,
  cluster_id text,
  cluster_label text,
  asset_source text NOT NULL DEFAULT 'target'::text CHECK (asset_source = ANY (ARRAY['existing'::text, 'target'::text, 'built'::text])),
  asset_type text,
  content_url text NOT NULL DEFAULT ''::text,
  content_title text,
  published_date date,
  geo_source_table text,
  geo_source_id text,
  generated_by_vibe_engine boolean,
  derived_from jsonb,
  asset_status text NOT NULL DEFAULT 'proposed'::text CHECK (asset_status = ANY (ARRAY['proposed'::text, 'published'::text, 'superseded'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  build_brief_id uuid,
  target text,
  drafted_payload text,
  content_provenance jsonb,
  revenue_opportunity_usd numeric,
  revenue_basis text CHECK (revenue_basis = ANY (ARRAY['actual'::text, 'modeled'::text, 'hybrid'::text, 'none'::text])),
  lifecycle_status text CHECK (lifecycle_status = ANY (ARRAY['generated'::text, 'internal_approved'::text, 'client_approved'::text, 'handed_off'::text, 'verified'::text, 'verify_failed'::text, 'needs_edit'::text, 'rejected'::text, 'superseded'::text])),
  content_tracking_url text,
  handed_off_at timestamp with time zone,
  verified_at timestamp with time zone,
  verify_evidence jsonb,
  verify_reason text,
  asset_revision integer DEFAULT 1,
  CONSTRAINT scout_assets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scout_asset_attribution (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scout_asset_id uuid NOT NULL,
  recommendation_id uuid,
  client_id uuid,
  cluster_id text,
  revenue_source text NOT NULL CHECK (revenue_source = ANY (ARRAY['ga4_landing_page'::text, 'attribution_events'::text, 'selection_events'::text, 'tier1_modeled'::text])),
  revenue_basis text NOT NULL DEFAULT 'none'::text CHECK (revenue_basis = ANY (ARRAY['actual'::text, 'modeled'::text, 'hybrid'::text, 'none'::text])),
  attribution_basis text NOT NULL,
  attributed_revenue_usd numeric,
  currency_code text DEFAULT 'USD'::text,
  window_start date,
  window_end date,
  coverage_score numeric,
  confidence_score numeric,
  revenue_inputs jsonb,
  measured_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scout_asset_attribution_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scout_build_briefs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recommendation_id uuid NOT NULL,
  scout_asset_id uuid,
  client_id uuid,
  cluster_id text,
  cluster_label text,
  asset_class text NOT NULL CHECK (asset_class = ANY (ARRAY['schema_jsonld'::text, 'llms_txt'::text, 'ai_bots_allowlist'::text, 'robots_txt'::text, 'faq_page'::text, 'blog'::text, 'case_study'::text, 'landing_page'::text])),
  target text NOT NULL,
  seed_signals jsonb,
  revenue_opportunity_usd numeric,
  revenue_basis text CHECK (revenue_basis = ANY (ARRAY['actual'::text, 'modeled'::text, 'hybrid'::text, 'none'::text])),
  status text NOT NULL DEFAULT 'drafted'::text CHECK (status = ANY (ARRAY['drafted'::text, 'queued'::text, 'generating'::text, 'generated'::text, 'superseded'::text])),
  edited_by text,
  edited_at timestamp with time zone,
  run_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scout_build_briefs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.scout_asset_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  scout_asset_id uuid NOT NULL,
  gate text NOT NULL CHECK (gate = ANY (ARRAY['internal'::text, 'external'::text])),
  decision text NOT NULL CHECK (decision = ANY (ARRAY['internal_approved'::text, 'needs_edit'::text, 'client_approved'::text, 'changes_requested'::text, 'rejected'::text])),
  reviewer text NOT NULL,
  notes text,
  asset_revision integer,
  decided_at timestamp with time zone DEFAULT now(),
  CONSTRAINT scout_asset_approvals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.recon_agent_onboarding (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  company_name text,
  domain text,
  description text,
  products jsonb DEFAULT '[]'::jsonb,
  services jsonb DEFAULT '[]'::jsonb,
  service_type text,
  area_served jsonb DEFAULT '[]'::jsonb,
  differentiators jsonb DEFAULT '[]'::jsonb,
  same_as jsonb DEFAULT '[]'::jsonb,
  logo_url text,
  contact_point jsonb,
  provenance jsonb DEFAULT '{}'::jsonb,
  source text NOT NULL DEFAULT 'recon_agent'::text CHECK (source = ANY (ARRAY['recon_agent'::text, 'manual'::text, 'blog_generations'::text])),
  confidence text DEFAULT 'low'::text CHECK (confidence = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  refreshed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  gaps jsonb DEFAULT '[]'::jsonb,
  competitive_narrative jsonb DEFAULT '{}'::jsonb,
  rating_value numeric,
  review_count integer,
  rating_source text,
  CONSTRAINT recon_agent_onboarding_pkey PRIMARY KEY (id)
);
CREATE TABLE public.attribution_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid,
  ga4_client_id text,
  crm_deal_id text,
  revenue numeric,
  converted_at timestamp with time zone,
  lead_source text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attribution_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crm_deals (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  crm_source text,
  crm_record_id text,
  amount numeric,
  currency_code text,
  stage text,
  closing_date date,
  email text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_deals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crm_leads (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  email text,
  lead_source text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT crm_leads_pkey PRIMARY KEY (id)
);
CREATE TABLE public.gsc_query_page_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  site_url text,
  metric_date date,
  query text,
  page text,
  clicks bigint,
  impressions bigint,
  ctr numeric,
  position numeric,
  country text,
  device text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  CONSTRAINT gsc_query_page_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ga4_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  property_id text,
  metric_date date,
  source text,
  medium text,
  campaign text,
  landing_page text,
  country text,
  device text,
  sessions bigint,
  engaged_sessions bigint,
  total_users bigint,
  new_users bigint,
  conversions numeric,
  revenue numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  CONSTRAINT ga4_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sov_computed (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  cluster_id text NOT NULL,
  cluster_name text,
  entity_name text NOT NULL,
  week_date date NOT NULL,
  sov_score double precision NOT NULL,
  word_count integer DEFAULT 0,
  query_count integer DEFAULT 0,
  answer_count integer DEFAULT 0,
  answer_source text DEFAULT 'ai_responses'::text,
  method_version text NOT NULL DEFAULT 'ts_v1'::text,
  computed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sov_computed_pkey PRIMARY KEY (id)
);
CREATE TABLE public.client_reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  client_id uuid NOT NULL,
  run_id uuid NOT NULL,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  model text NOT NULL,
  headline text NOT NULL,
  executive_summary text NOT NULL,
  sov_narrative text NOT NULL,
  competitive_narrative text NOT NULL,
  signals_narrative text NOT NULL,
  recommendations_narrative text NOT NULL,
  CONSTRAINT client_reports_pkey PRIMARY KEY (id),
  CONSTRAINT client_reports_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(client_id),
  CONSTRAINT client_reports_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.cycle_runs(run_id)
);
CREATE TABLE public.ai_sov (
  id uuid NOT NULL,
  user_id uuid,
  client_id uuid NOT NULL,
  cluster_name text,
  sov jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT ai_sov_pkey PRIMARY KEY (id),
  CONSTRAINT ai_sov_client_id_fk FOREIGN KEY (client_id) REFERENCES public.onboarding(client_id)
);
CREATE TABLE public.ai_monitoring (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid DEFAULT gen_random_uuid(),
  request_payload json,
  citations_data json,
  companies_data json,
  answers_list json,
  citations_list json,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  client_id uuid NOT NULL,
  cluster_id text,
  cluster_name text DEFAULT 'NULL'::text,
  sov jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT ai_monitoring_pkey PRIMARY KEY (id),
  CONSTRAINT ai_monitoring_client_id_fk FOREIGN KEY (client_id) REFERENCES public.onboarding(client_id)
);
CREATE TABLE public.ai_visibility_schema_migrations (
  version text NOT NULL,
  checksum text NOT NULL,
  applied_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_schema_migrations_pkey PRIMARY KEY (version)
);
CREATE TABLE public.ai_visibility_companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  canonical_name text NOT NULL,
  normalized_name text NOT NULL UNIQUE,
  official_domains jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_visibility_company_aliases (
  company_id uuid NOT NULL,
  alias text NOT NULL,
  normalized_alias text NOT NULL,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_company_aliases_pkey PRIMARY KEY (company_id, normalized_alias),
  CONSTRAINT ai_visibility_company_aliases_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.ai_visibility_companies(id)
);
CREATE TABLE public.ai_visibility_client_companies (
  client_id uuid NOT NULL,
  company_id uuid NOT NULL,
  relationship text NOT NULL CHECK (relationship = ANY (ARRAY['client'::text, 'competitor'::text, 'other_tracked'::text])),
  priority integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_client_companies_pkey PRIMARY KEY (client_id, company_id),
  CONSTRAINT ai_visibility_client_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.ai_visibility_companies(id)
);
CREATE TABLE public.ai_visibility_monitor_queries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  query_key text NOT NULL UNIQUE,
  client_id uuid NOT NULL,
  cluster_id text,
  cluster_name text,
  base_query text NOT NULL,
  normalized_base_query text NOT NULL,
  service text NOT NULL,
  method text NOT NULL,
  configuration_hash text NOT NULL,
  configuration_completeness text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_monitor_queries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_visibility_run_processing (
  run_id uuid NOT NULL,
  client_id uuid NOT NULL,
  monitor_query_id uuid NOT NULL,
  source_created_at timestamp with time zone NOT NULL,
  status text NOT NULL,
  is_valid boolean NOT NULL,
  invalid_reason text,
  pipeline_version text NOT NULL,
  data_quality_flags jsonb NOT NULL DEFAULT '[]'::jsonb,
  normalized_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_run_processing_pkey PRIMARY KEY (run_id),
  CONSTRAINT ai_visibility_run_processing_monitor_query_id_fkey FOREIGN KEY (monitor_query_id) REFERENCES public.ai_visibility_monitor_queries(id)
);
CREATE TABLE public.ai_visibility_answers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL,
  answer_number integer NOT NULL,
  answer_text text NOT NULL,
  answer_hash text NOT NULL,
  word_count integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_answers_pkey PRIMARY KEY (id),
  CONSTRAINT ai_visibility_answers_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.ai_visibility_run_processing(run_id)
);
CREATE TABLE public.ai_visibility_run_company_metrics (
  run_id uuid NOT NULL,
  company_id uuid NOT NULL,
  literal_answer_count integer NOT NULL,
  literal_answer_numbers jsonb NOT NULL,
  literal_visibility double precision NOT NULL,
  literal_total_mentions integer NOT NULL,
  upstream_count double precision,
  upstream_visibility double precision,
  upstream_word_count double precision,
  metric_difference double precision,
  data_quality_flags jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_run_company_metrics_pkey PRIMARY KEY (run_id, company_id),
  CONSTRAINT ai_visibility_run_company_metrics_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.ai_visibility_run_processing(run_id),
  CONSTRAINT ai_visibility_run_company_metrics_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.ai_visibility_companies(id)
);
CREATE TABLE public.ai_visibility_answer_company_mentions (
  answer_id uuid NOT NULL,
  company_id uuid NOT NULL,
  literal_mention_count integer NOT NULL,
  first_position integer,
  context_snippets jsonb NOT NULL DEFAULT '[]'::jsonb,
  detection_method text NOT NULL DEFAULT 'boundary_literal_alias'::text,
  confidence double precision NOT NULL DEFAULT 1.0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_answer_company_mentions_pkey PRIMARY KEY (answer_id, company_id, detection_method),
  CONSTRAINT ai_visibility_answer_company_mentions_answer_id_fkey FOREIGN KEY (answer_id) REFERENCES public.ai_visibility_answers(id),
  CONSTRAINT ai_visibility_answer_company_mentions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.ai_visibility_companies(id)
);
CREATE TABLE public.ai_visibility_citation_pages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  normalized_url text NOT NULL UNIQUE,
  domain text NOT NULL,
  publisher_company_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_citation_pages_pkey PRIMARY KEY (id),
  CONSTRAINT ai_visibility_citation_pages_publisher_company_id_fkey FOREIGN KEY (publisher_company_id) REFERENCES public.ai_visibility_companies(id)
);
CREATE TABLE public.ai_visibility_answer_citations (
  answer_id uuid NOT NULL,
  page_id uuid NOT NULL,
  original_url text NOT NULL,
  title text,
  raw_occurrence_count integer NOT NULL,
  start_index integer,
  end_index integer,
  position_quality text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_answer_citations_pkey PRIMARY KEY (answer_id, page_id),
  CONSTRAINT ai_visibility_answer_citations_answer_id_fkey FOREIGN KEY (answer_id) REFERENCES public.ai_visibility_answers(id),
  CONSTRAINT ai_visibility_answer_citations_page_id_fkey FOREIGN KEY (page_id) REFERENCES public.ai_visibility_citation_pages(id)
);
CREATE TABLE public.ai_visibility_run_comparisons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  monitor_query_id uuid NOT NULL,
  previous_run_id uuid NOT NULL,
  current_run_id uuid NOT NULL,
  comparison_type text NOT NULL,
  comparability_score double precision NOT NULL,
  comparability_flags jsonb NOT NULL DEFAULT '[]'::jsonb,
  structured_delta jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_run_comparisons_pkey PRIMARY KEY (id),
  CONSTRAINT ai_visibility_run_comparisons_monitor_query_id_fkey FOREIGN KEY (monitor_query_id) REFERENCES public.ai_visibility_monitor_queries(id)
);
CREATE TABLE public.ai_visibility_page_fetch_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  page_id uuid NOT NULL,
  client_id uuid NOT NULL,
  priority integer NOT NULL DEFAULT 0,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  attempts integer NOT NULL DEFAULT 0,
  run_after timestamp with time zone NOT NULL DEFAULT now(),
  locked_at timestamp with time zone,
  locked_by text,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_page_fetch_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_visibility_page_fetch_jobs_page_id_fkey FOREIGN KEY (page_id) REFERENCES public.ai_visibility_citation_pages(id)
);
CREATE TABLE public.ai_visibility_page_snapshots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  page_id uuid NOT NULL,
  retrieved_at timestamp with time zone NOT NULL DEFAULT now(),
  http_status integer,
  final_url text,
  content_type text,
  title text,
  main_text text,
  main_text_hash text,
  raw_content_hash text,
  etag text,
  last_modified_header text,
  structured_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  fetch_method text,
  fetch_error text,
  robots_allowed boolean,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_page_snapshots_pkey PRIMARY KEY (id),
  CONSTRAINT ai_visibility_page_snapshots_page_id_fkey FOREIGN KEY (page_id) REFERENCES public.ai_visibility_citation_pages(id)
);
CREATE TABLE public.ai_visibility_page_company_mentions (
  snapshot_id uuid NOT NULL,
  company_id uuid NOT NULL,
  mention_count integer NOT NULL,
  mentioned_in_title boolean NOT NULL DEFAULT false,
  mentioned_in_heading boolean NOT NULL DEFAULT false,
  links_to_official_domain boolean NOT NULL DEFAULT false,
  publisher_is_company boolean NOT NULL DEFAULT false,
  mention_role text NOT NULL,
  context_snippets jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence double precision NOT NULL DEFAULT 1.0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_page_company_mentions_pkey PRIMARY KEY (snapshot_id, company_id),
  CONSTRAINT ai_visibility_page_company_mentions_snapshot_id_fkey FOREIGN KEY (snapshot_id) REFERENCES public.ai_visibility_page_snapshots(id),
  CONSTRAINT ai_visibility_page_company_mentions_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.ai_visibility_companies(id)
);
CREATE TABLE public.ai_visibility_page_snapshot_diffs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  page_id uuid NOT NULL,
  previous_snapshot_id uuid NOT NULL,
  current_snapshot_id uuid NOT NULL,
  text_similarity double precision,
  material_change boolean NOT NULL,
  change_summary jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_page_snapshot_diffs_pkey PRIMARY KEY (id),
  CONSTRAINT ai_visibility_page_snapshot_diffs_page_id_fkey FOREIGN KEY (page_id) REFERENCES public.ai_visibility_citation_pages(id),
  CONSTRAINT ai_visibility_page_snapshot_diffs_previous_snapshot_id_fkey FOREIGN KEY (previous_snapshot_id) REFERENCES public.ai_visibility_page_snapshots(id),
  CONSTRAINT ai_visibility_page_snapshot_diffs_current_snapshot_id_fkey FOREIGN KEY (current_snapshot_id) REFERENCES public.ai_visibility_page_snapshots(id)
);
CREATE TABLE public.ai_visibility_signals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  idempotency_key text NOT NULL UNIQUE,
  client_id uuid NOT NULL,
  company_id uuid,
  signal_type text NOT NULL,
  severity double precision NOT NULL,
  confidence text NOT NULL,
  structured_payload jsonb NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'active'::text,
  CONSTRAINT ai_visibility_signals_pkey PRIMARY KEY (id),
  CONSTRAINT ai_visibility_signals_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.ai_visibility_companies(id)
);
CREATE TABLE public.ai_visibility_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  idempotency_key text NOT NULL UNIQUE,
  client_id uuid NOT NULL,
  company_id uuid NOT NULL,
  company_name text NOT NULL,
  analysis_start timestamp with time zone,
  analysis_end timestamp with time zone,
  report_version text NOT NULL,
  status text NOT NULL,
  structured_report jsonb,
  generated_at timestamp with time zone,
  last_error text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ai_visibility_reports_pkey PRIMARY KEY (id),
  CONSTRAINT ai_visibility_reports_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.ai_visibility_companies(id)
);
CREATE TABLE public.aivc_pipeline_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  client_id uuid NOT NULL,
  canonical_name text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'partial'::text, 'completed'::text, 'failed'::text])),
  requested_options jsonb NOT NULL DEFAULT '{}'::jsonb,
  component_versions jsonb NOT NULL DEFAULT '{}'::jsonb,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  error_summary text,
  combined_bundle_id text,
  combined_bundle_checksum text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aivc_pipeline_runs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.aivc_pipeline_stages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parent_run_id uuid NOT NULL,
  stage_name text NOT NULL,
  attempt integer NOT NULL DEFAULT 1 CHECK (attempt > 0),
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'partial'::text, 'failed'::text, 'skipped'::text])),
  required boolean NOT NULL DEFAULT true,
  child_run_id text,
  artifact_id text,
  input_checksum text,
  output_checksum text,
  lease_owner text,
  lease_expires_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  error_type text,
  error_message text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aivc_pipeline_stages_pkey PRIMARY KEY (id),
  CONSTRAINT aivc_pipeline_stages_parent_run_id_fkey FOREIGN KEY (parent_run_id) REFERENCES public.aivc_pipeline_runs(id)
);
CREATE TABLE public.aivc_signal_bundles (
  bundle_id text NOT NULL,
  parent_run_id uuid,
  producer text NOT NULL,
  producer_run_id text NOT NULL,
  client_id uuid NOT NULL,
  schema_version text NOT NULL,
  analysis_start timestamp with time zone,
  analysis_end timestamp with time zone,
  status text NOT NULL CHECK (status = ANY (ARRAY['complete'::text, 'partial'::text, 'failed'::text])),
  payload jsonb NOT NULL,
  checksum text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aivc_signal_bundles_pkey PRIMARY KEY (bundle_id),
  CONSTRAINT aivc_signal_bundles_parent_run_id_fkey FOREIGN KEY (parent_run_id) REFERENCES public.aivc_pipeline_runs(id)
);
CREATE TABLE public.aivc_delivery_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  parent_run_id uuid NOT NULL,
  client_id uuid NOT NULL,
  channel text NOT NULL,
  destination_key text NOT NULL,
  artifact_key text NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'delivered'::text, 'failed'::text, 'skipped'::text])),
  attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  response_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  delivered_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT aivc_delivery_log_pkey PRIMARY KEY (id),
  CONSTRAINT aivc_delivery_log_parent_run_id_fkey FOREIGN KEY (parent_run_id) REFERENCES public.aivc_pipeline_runs(id)
);