-- agent_db_geo_schema.sql — create GEO mirror tables in the agent DB (Agentic_db) so the existing cron can fill them.
-- Purpose: schema-only DDL. The 30-min GEO->Agentic_db sync already exists; it just needs these target tables
--          to land rows into, and the Scout GEO-reuse bridge then reads them as ordinary public.<table> queries.
-- Scope: RUN ONCE in the Agentic_db SQL editor (runs as `postgres`). Creates 7 mirror tables + RLS + indexes.
--        No FDW, no cross-DB, no app-side mapping. Does NOT touch clients / sov_weekly / ai_responses.
--
-- Column names/types mirror the GEO source (see master docs/geo_db_schema.sql) so a `select *`-style sync
-- copies cleanly. Mirrors are constraint-light (PK only, no FK/CHECK) so the cron can upsert in any order.
-- RLS is enabled with NO policies: anon/authenticated are denied, while the cron (writes) and Scout's
-- service key (reads) use service_role/postgres, which BYPASS RLS — so GEO data is never exposed via the
-- public API. NOTE: the cron must write as the same privileged role it already uses for clients/sov_weekly.

-- ───────────────────────────────────────────────────────────────────────────
-- PART 1 — mirror tables (create if absent; bigint ids accept the GEO id on copy)
-- ───────────────────────────────────────────────────────────────────────────

-- report_data.client_id is TEXT (not uuid) — the bridge filters it as a string.
create table if not exists public.report_data (
  id bigint generated by default as identity primary key,
  client_id text,
  report_id text,
  ai_visibility_data json,
  website_files_data json,
  schema_data json,
  created_at timestamptz not null default now(),
  company_website text,
  company_name text,
  final_points json
);

create table if not exists public.onboarding (
  id uuid primary key default gen_random_uuid(),
  client_id uuid unique,
  company_domain text,
  company_name text,
  target_region text,
  created_at timestamptz,
  updated_at timestamptz,
  status boolean,
  industry text,
  target_audience text,
  competitors jsonb,
  topics jsonb,
  category_tags jsonb,
  primary_goal text,
  tone_preference text,
  average_order_value numeric,
  conversion_rate numeric,
  estimated_ctr numeric,
  currency varchar,
  client_plan text,
  company_website text,
  demo_ready boolean,
  company_description text,
  competitors_url jsonb,
  lead_source text
);

create table if not exists public.user_metrics (
  client_id uuid primary key,
  ga4_refresh_token text,
  ga4_property_id text,
  created_at timestamptz,
  updated_at timestamptz,
  average_order_value numeric,
  conversion_rate numeric,
  estimated_ctr numeric,
  gsc_refresh_token text,
  gsc_site_url text
);

create table if not exists public.queries_groups_data (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid,
  queries_groups_data jsonb,
  client_id uuid,
  updated_at timestamptz
);

create table if not exists public.keywords_groups_data (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid,
  keywords_groups_data jsonb,
  client_id uuid
);

create table if not exists public.company_scraped_data_cache (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  url text,
  source text,
  summary text,
  count bigint,
  last_refreshed timestamptz
);

create table if not exists public.selection_events (
  id uuid primary key default gen_random_uuid(),
  client_id uuid,
  event_type varchar,
  platform varchar,
  query_text text,
  response_text text,
  was_selected boolean,
  competitors_mentioned text[],
  created_at timestamptz default now(),
  attribution_event_id uuid,
  revenue_attributed numeric
);

-- ───────────────────────────────────────────────────────────────────────────
-- PART 1b — revenue mirror tables (Tier-1 Phase B). Synced by scout-sync.
-- ───────────────────────────────────────────────────────────────────────────

-- GSC demand + volume. Keyed on site_url (maps to user_metrics.gsc_site_url).
-- NOTE: ctr is a FRACTION (0.031), NOT a percentage — unlike onboarding.estimated_ctr which IS a percentage.
-- id is uuid (copied straight from the GEO source id) so scout-sync can upsert onConflict:"id" without
-- deduping on the nullable natural key (NULLs are distinct -> silent dupes). updated_at is the sync cursor.
create table if not exists public.gsc_query_page_metrics (
  id           uuid primary key default gen_random_uuid(),
  site_url     text,
  metric_date  date,
  query        text,
  page         text,
  clicks       bigint,
  impressions  bigint,
  ctr          numeric,
  position     numeric,
  country      text,
  device       text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz
);

-- GA4 revenue by landing_page + channel. Keyed on property_id (user_metrics.ga4_property_id).
-- id is uuid (copied from the GEO source id) so scout-sync upserts onConflict:"id"; updated_at is the cursor.
create table if not exists public.ga4_metrics (
  id                uuid primary key default gen_random_uuid(),
  property_id       text,
  metric_date       date,
  source            text,
  medium            text,
  campaign          text,
  landing_page      text,
  country           text,
  device            text,
  sessions          bigint,
  engaged_sessions  bigint,
  total_users       bigint,
  new_users         bigint,
  conversions       numeric,
  revenue           numeric,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz
);

-- Per-client converted revenue (attribution Channel B; has client_id). Vendor CRM (crm_deals/crm_leads) is
-- Multiplier AI's OWN sales pipeline (no client_id) and is intentionally NOT mirrored here — it must never
-- feed client revenue attribution.
create table if not exists public.attribution_events (
  id             uuid primary key default gen_random_uuid(),
  client_id      uuid,
  ga4_client_id  text,
  crm_deal_id    text,
  revenue        numeric,
  converted_at   timestamptz,
  lead_source    text,
  created_at     timestamptz not null default now()
);

-- ───────────────────────────────────────────────────────────────────────────
-- PART 2 — RLS (deny anon/authenticated; cron + service key bypass). No policies on purpose.
-- ───────────────────────────────────────────────────────────────────────────
alter table public.report_data                enable row level security;
alter table public.onboarding                 enable row level security;
alter table public.user_metrics               enable row level security;
alter table public.queries_groups_data        enable row level security;
alter table public.keywords_groups_data       enable row level security;
alter table public.company_scraped_data_cache enable row level security;
alter table public.selection_events           enable row level security;
alter table public.gsc_query_page_metrics enable row level security;
alter table public.ga4_metrics            enable row level security;
alter table public.attribution_events     enable row level security;

-- ───────────────────────────────────────────────────────────────────────────
-- PART 3 — indexes for the bridge's filters
-- ───────────────────────────────────────────────────────────────────────────
create index if not exists idx_report_data_client_created on public.report_data (client_id, created_at desc);
create index if not exists idx_selection_events_client    on public.selection_events (client_id);
create index if not exists idx_queries_groups_client      on public.queries_groups_data (client_id);
create index if not exists idx_keywords_groups_client     on public.keywords_groups_data (client_id);
create index if not exists idx_scraped_cache_url          on public.company_scraped_data_cache (url);
-- onboarding.client_id is UNIQUE (implicit index); user_metrics.client_id is the PK.
create index if not exists idx_gsc_site_date   on public.gsc_query_page_metrics (site_url, metric_date desc);
create index if not exists idx_gsc_query        on public.gsc_query_page_metrics (site_url, query);
create index if not exists idx_ga4_prop_date    on public.ga4_metrics (property_id, metric_date desc);
create index if not exists idx_ga4_landing      on public.ga4_metrics (property_id, landing_page);
create index if not exists idx_attr_client      on public.attribution_events (client_id);

-- Reload the PostgREST schema cache so the Scout API sees the new tables immediately.
notify pgrst, 'reload schema';

-- ───────────────────────────────────────────────────────────────────────────
-- PART 4 — verify. Counts are 0 until the existing GEO->Agentic_db cron next runs.
-- After the next sync, re-run this to confirm rows are landing.
-- ───────────────────────────────────────────────────────────────────────────
select 'report_data'                as tbl, count(*) from public.report_data
union all select 'onboarding',                count(*) from public.onboarding
union all select 'user_metrics',              count(*) from public.user_metrics
union all select 'queries_groups_data',       count(*) from public.queries_groups_data
union all select 'keywords_groups_data',      count(*) from public.keywords_groups_data
union all select 'company_scraped_data_cache', count(*) from public.company_scraped_data_cache
union all select 'selection_events',          count(*) from public.selection_events
union all select 'gsc_query_page_metrics',   count(*) from public.gsc_query_page_metrics
union all select 'ga4_metrics',              count(*) from public.ga4_metrics
union all select 'attribution_events',       count(*) from public.attribution_events;

-- ───────────────────────────────────────────────────────────────────────────
-- TEARDOWN (if ever needed):
--   drop table if exists public.report_data, public.onboarding, public.user_metrics,
--     public.queries_groups_data, public.keywords_groups_data,
--     public.company_scraped_data_cache, public.selection_events,
--     public.gsc_query_page_metrics, public.ga4_metrics,
--     public.attribution_events cascade;
-- ───────────────────────────────────────────────────────────────────────────
